version: '3.5'
services:
  frontend:
    image: frontend
    ports:
      - 5000:5000
  backend:
    image: backend
    ports:
      - 8000:8000
    volumes:
      - ./logs.txt:/backend-example-docker/logs.txt
    environment:
      - REDIS=redis
  redis:
    image: redis
